// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euzvagclzldyybnyvxyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1enZhZ2NsemxkeXlibnl2eHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjQ4ODgsImV4cCI6MjA2ODAwMDg4OH0.W_PURfIMmpLY1r9RaohIQw-zIwrXEjX-mCsexOBsvWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});